




#! /bin/sh
#
# Configure debugging options for es40.
#
echo "This is the debug-options configuration script for the ES40 emulator"
echo "If you don't want any debugging options enabled, answer YES to the"
echo "following question"
echo ""
cat >src/config_debug.h <<EOF
// This file contains the debug configuration options.
// This file was generated by configure_1.sh
EOF
  while true; do
    echo -n " Do you want the defaults for all options? [yes]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="yes"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      defopt="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      defopt="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

  if test "$defopt" = "no"; then
    while true; do
    echo -n " Do you want to show the cycle counter? [yes]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="yes"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      cyc="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      cyc="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

    if test "$cyc" = "no"; then
      cat >>src/config_debug.h <<EOF

// Disable the cycle counter
#define HIDE_COUNTER 1
EOF
    else
      cat >>src/config_debug.h <<EOF

// Enable the cycle counter
//#define HIDE_COUNTER 1
EOF
    fi
    while true; do
    echo -n " Do you want to enable VGA debugging? [no]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="no"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      dbg="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      dbg="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

  if test "$dbg" = "yes"; then
    cat >>src/config_debug.h <<EOF

// Enable VGA debugging
#define DEBUG_VGA 1
EOF
  else
    cat >>src/config_debug.h <<EOF

// Disable VGA debugging
//#define DEBUG_VGA 1 
EOF
  fi

    while true; do
    echo -n " Do you want to enable Serial Port debugging? [no]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="no"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      dbg="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      dbg="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

  if test "$dbg" = "yes"; then
    cat >>src/config_debug.h <<EOF

// Enable Serial Port debugging
#define DEBUG_SERIAL 1
EOF
  else
    cat >>src/config_debug.h <<EOF

// Disable Serial Port debugging
//#define DEBUG_SERIAL 1 
EOF
  fi

    while true; do
    echo -n " Do you want to enable one or more IDE debugging options? [no]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="no"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      ide="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      ide="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

    if test "$ide" = "yes"; then
      while true; do
    echo -n " Do you want to enable all IDE debugging? [no]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="no"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      dbg="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      dbg="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

  if test "$dbg" = "yes"; then
    cat >>src/config_debug.h <<EOF

// Enable all IDE debugging
#define DEBUG_IDE 1
EOF
  else
    cat >>src/config_debug.h <<EOF

// Disable all IDE debugging
//#define DEBUG_IDE 1 
EOF
  fi

      if test "$dbg" = "no"; then
        while true; do
    echo -n " Do you want to enable IDE Busmaster debugging? [no]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="no"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      dbg="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      dbg="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

  if test "$dbg" = "yes"; then
    cat >>src/config_debug.h <<EOF

// Enable IDE Busmaster debugging
#define DEBUG_IDE_BUSMASTER 1
EOF
  else
    cat >>src/config_debug.h <<EOF

// Disable IDE Busmaster debugging
//#define DEBUG_IDE_BUSMASTER 1 
EOF
  fi

        while true; do
    echo -n " Do you want to enable IDE Command debugging? [no]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="no"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      dbg="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      dbg="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

  if test "$dbg" = "yes"; then
    cat >>src/config_debug.h <<EOF

// Enable IDE Command debugging
#define DEBUG_IDE_COMMAND 1
EOF
  else
    cat >>src/config_debug.h <<EOF

// Disable IDE Command debugging
//#define DEBUG_IDE_COMMAND 1 
EOF
  fi

        while true; do
    echo -n " Do you want to enable IDE DMA debugging? [no]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="no"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      dbg="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      dbg="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

  if test "$dbg" = "yes"; then
    cat >>src/config_debug.h <<EOF

// Enable IDE DMA debugging
#define DEBUG_IDE_DMA 1
EOF
  else
    cat >>src/config_debug.h <<EOF

// Disable IDE DMA debugging
//#define DEBUG_IDE_DMA 1 
EOF
  fi

        while true; do
    echo -n " Do you want to enable IDE Interrupt debugging? [no]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="no"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      dbg="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      dbg="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

  if test "$dbg" = "yes"; then
    cat >>src/config_debug.h <<EOF

// Enable IDE Interrupt debugging
#define DEBUG_IDE_INTERRUPT 1
EOF
  else
    cat >>src/config_debug.h <<EOF

// Disable IDE Interrupt debugging
//#define DEBUG_IDE_INTERRUPT 1 
EOF
  fi

        while true; do
    echo -n " Do you want to enable IDE Command Register debugging? [no]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="no"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      dbg="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      dbg="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

  if test "$dbg" = "yes"; then
    cat >>src/config_debug.h <<EOF

// Enable IDE Command Register debugging
#define DEBUG_IDE_REG_COMMAND 1
EOF
  else
    cat >>src/config_debug.h <<EOF

// Disable IDE Command Register debugging
//#define DEBUG_IDE_REG_COMMAND 1 
EOF
  fi

        while true; do
    echo -n " Do you want to enable IDE Control Register debugging? [no]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="no"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      dbg="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      dbg="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

  if test "$dbg" = "yes"; then
    cat >>src/config_debug.h <<EOF

// Enable IDE Control Register debugging
#define DEBUG_IDE_REG_CONTROL 1
EOF
  else
    cat >>src/config_debug.h <<EOF

// Disable IDE Control Register debugging
//#define DEBUG_IDE_REG_CONTROL 1 
EOF
  fi

        while true; do
    echo -n " Do you want to enable IDE ATAPI Packet debugging? [no]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="no"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      dbg="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      dbg="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

  if test "$dbg" = "yes"; then
    cat >>src/config_debug.h <<EOF

// Enable IDE ATAPI Packet debugging
#define DEBUG_IDE_PACKET 1
EOF
  else
    cat >>src/config_debug.h <<EOF

// Disable IDE ATAPI Packet debugging
//#define DEBUG_IDE_PACKET 1 
EOF
  fi

        while true; do
    echo -n " Do you want to enable IDE Thread debugging? [no]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="no"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      dbg="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      dbg="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

  if test "$dbg" = "yes"; then
    cat >>src/config_debug.h <<EOF

// Enable IDE Thread debugging
#define DEBUG_IDE_THREADS 1
EOF
  else
    cat >>src/config_debug.h <<EOF

// Disable IDE Thread debugging
//#define DEBUG_IDE_THREADS 1 
EOF
  fi

        while true; do
    echo -n " Do you want to enable IDE Mutexes debugging? [no]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="no"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      dbg="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      dbg="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

  if test "$dbg" = "yes"; then
    cat >>src/config_debug.h <<EOF

// Enable IDE Mutexes debugging
#define DEBUG_IDE_LOCKS 1
EOF
  else
    cat >>src/config_debug.h <<EOF

// Disable IDE Mutexes debugging
//#define DEBUG_IDE_LOCKS 1 
EOF
  fi

      fi
    fi
    while true; do
    echo -n " Do you want to enable unknown memory access debugging? [no]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="no"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      dbg="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      dbg="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

  if test "$dbg" = "yes"; then
    cat >>src/config_debug.h <<EOF

// Enable unknown memory access debugging
#define DEBUG_UNKMEM 1
EOF
  else
    cat >>src/config_debug.h <<EOF

// Disable unknown memory access debugging
//#define DEBUG_UNKMEM 1 
EOF
  fi

    while true; do
    echo -n " Do you want to enable PCI debugging? [no]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="no"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      dbg="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      dbg="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

  if test "$dbg" = "yes"; then
    cat >>src/config_debug.h <<EOF

// Enable PCI debugging
#define DEBUG_PCI 1
EOF
  else
    cat >>src/config_debug.h <<EOF

// Disable PCI debugging
//#define DEBUG_PCI 1 
EOF
  fi

    while true; do
    echo -n " Do you want to enable Translationbuffer debugging? [no]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="no"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      dbg="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      dbg="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

  if test "$dbg" = "yes"; then
    cat >>src/config_debug.h <<EOF

// Enable Translationbuffer debugging
#define DEBUG_TB 1
EOF
  else
    cat >>src/config_debug.h <<EOF

// Disable Translationbuffer debugging
//#define DEBUG_TB 1 
EOF
  fi

    while true; do
    echo -n " Do you want to enable I/O Port Access debugging? [no]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="no"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      dbg="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      dbg="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

  if test "$dbg" = "yes"; then
    cat >>src/config_debug.h <<EOF

// Enable I/O Port Access debugging
#define DEBUG_PORTACCESS 1
EOF
  else
    cat >>src/config_debug.h <<EOF

// Disable I/O Port Access debugging
//#define DEBUG_PORTACCESS 1 
EOF
  fi

    while true; do
    echo -n " Do you want to enable SCSI debugging? [no]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="no"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      dbg="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      dbg="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

  if test "$dbg" = "yes"; then
    cat >>src/config_debug.h <<EOF

// Enable SCSI debugging
#define DEBUG_SCSI 1
EOF
  else
    cat >>src/config_debug.h <<EOF

// Disable SCSI debugging
//#define DEBUG_SCSI 1 
EOF
  fi

    while true; do
    echo -n " Do you want to enable Keyboard debugging? [no]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="no"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      dbg="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      dbg="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

  if test "$dbg" = "yes"; then
    cat >>src/config_debug.h <<EOF

// Enable Keyboard debugging
#define DEBUG_KBD 1
EOF
  else
    cat >>src/config_debug.h <<EOF

// Disable Keyboard debugging
//#define DEBUG_KBD 1 
EOF
  fi

    while true; do
    echo -n " Do you want to enable Programmable Interrupt Controller (PIC) debugging? [no]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="no"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      dbg="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      dbg="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

  if test "$dbg" = "yes"; then
    cat >>src/config_debug.h <<EOF

// Enable Programmable Interrupt Controller (PIC) debugging
#define DEBUG_PIC 1
EOF
  else
    cat >>src/config_debug.h <<EOF

// Disable Programmable Interrupt Controller (PIC) debugging
//#define DEBUG_PIC 1 
EOF
  fi

    while true; do
    echo -n " Do you want to enable Printer port debugging? [no]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="no"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      dbg="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      dbg="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

  if test "$dbg" = "yes"; then
    cat >>src/config_debug.h <<EOF

// Enable Printer port debugging
#define DEBUG_LPT 1
EOF
  else
    cat >>src/config_debug.h <<EOF

// Disable Printer port debugging
//#define DEBUG_LPT 1 
EOF
  fi

    while true; do
    echo -n " Do you want to enable USB Controller debugging? [no]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="no"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      dbg="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      dbg="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

  if test "$dbg" = "yes"; then
    cat >>src/config_debug.h <<EOF

// Enable USB Controller debugging
#define DEBUG_USB 1
EOF
  else
    cat >>src/config_debug.h <<EOF

// Disable USB Controller debugging
//#define DEBUG_USB 1 
EOF
  fi

    while true; do
    echo -n " Do you want to enable Symbios SCSI Controller debugging? [no]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="no"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      dbg="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      dbg="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

  if test "$dbg" = "yes"; then
    cat >>src/config_debug.h <<EOF

// Enable Symbios SCSI Controller debugging
#define DEBUG_SYM 1
EOF
  else
    cat >>src/config_debug.h <<EOF

// Disable Symbios SCSI Controller debugging
//#define DEBUG_SYM 1 
EOF
  fi

    while true; do
    echo -n " Do you want to enable DMA Controller debugging? [no]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="no"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      dbg="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      dbg="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

  if test "$dbg" = "yes"; then
    cat >>src/config_debug.h <<EOF

// Enable DMA Controller debugging
#define DEBUG_DMA 1
EOF
  else
    cat >>src/config_debug.h <<EOF

// Disable DMA Controller debugging
//#define DEBUG_DMA 1 
EOF
  fi

    while true; do
    echo -n " Do you want to enable backtrace on SIGSEGV debugging? [no]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="no"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      dbg="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      dbg="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

  if test "$dbg" = "yes"; then
    cat >>src/config_debug.h <<EOF

// Enable backtrace on SIGSEGV debugging
#define DEBUG_BACKTRACE 1
EOF
  else
    cat >>src/config_debug.h <<EOF

// Disable backtrace on SIGSEGV debugging
//#define DEBUG_BACKTRACE 1 
EOF
  fi

    while true; do
    echo -n " Do you want to enable mutex debugging? [no]: "
    read ac_tmp 
    if test "X$ac_tmp" = "X"; then
      ac_tmp="no"
    fi
    if test "$ac_tmp" = "y" -o "$ac_tmp" = "ye" -o "$ac_tmp" = "yes"; then
      dbg="yes"
      break
    fi
    if test "$ac_tmp" = "n" -o "$ac_tmp" = "no"; then
      dbg="no"
      break
    fi
    echo "Invalid value; please enter yes or no"
  done

  if test "$dbg" = "yes"; then
    cat >>src/config_debug.h <<EOF

// Enable mutex debugging
#define DEBUG_LOCKS 1
EOF
  else
    cat >>src/config_debug.h <<EOF

// Disable mutex debugging
//#define DEBUG_LOCKS 1 
EOF
  fi

  fi

