// This file contains the debug configuration options.
// This file was generated by configure_1.sh

// Enable the cycle counter
//#define HIDE_COUNTER 1

// Disable VGA debugging
//#define DEBUG_VGA 1 

// Disable Serial Port debugging
//#define DEBUG_SERIAL 1 

// Disable all IDE debugging
//#define DEBUG_IDE 1 

// Disable IDE Busmaster debugging
//#define DEBUG_IDE_BUSMASTER 1 

// Disable IDE Command debugging
//#define DEBUG_IDE_COMMAND 1 

// Disable IDE DMA debugging
//#define DEBUG_IDE_DMA 1 

// Disable IDE Interrupt debugging
//#define DEBUG_IDE_INTERRUPT 1 

// Disable IDE Command Register debugging
//#define DEBUG_IDE_REG_COMMAND 1 

// Disable IDE Control Register debugging
//#define DEBUG_IDE_REG_CONTROL 1 

// Disable IDE ATAPI Packet debugging
//#define DEBUG_IDE_PACKET 1 

// Disable IDE Thread debugging
//#define DEBUG_IDE_THREADS 1 

// Disable IDE Mutexes debugging
//#define DEBUG_IDE_LOCKS 1 

// Disable unknown memory access debugging
//#define DEBUG_UNKMEM 1 

// Disable PCI debugging
//#define DEBUG_PCI 1 

// Disable Translationbuffer debugging
//#define DEBUG_TB 1 

// Disable I/O Port Access debugging
//#define DEBUG_PORTACCESS 1 

// Disable SCSI debugging
//#define DEBUG_SCSI 1 

// Disable Keyboard debugging
//#define DEBUG_KBD 1 

// Disable Programmable Interrupt Controller (PIC) debugging
//#define DEBUG_PIC 1 

// Disable Printer port debugging
//#define DEBUG_LPT 1 

// Disable USB Controller debugging
//#define DEBUG_USB 1 

// Disable Symbios SCSI Controller debugging
//#define DEBUG_SYM 1 

// Disable DMA Controller debugging
//#define DEBUG_DMA 1 

// Disable backtrace on SIGSEGV debugging
//#define DEBUG_BACKTRACE 1 

// Disable mutex debugging
//#define DEBUG_LOCKS 1 
